table 'Measure Table'
	lineageTag: 60bb3474-0155-478e-8fb3-30cca490a631

	measure 'Quantity Sold' =
			
			SUM(
			    'Sales Data'[OrderQuantity]
			)
		formatString: #,0
		lineageTag: 53151110-c4a7-48d2-a977-8951c289e015

	measure 'Quantity Returned' =
			
			SUM(
			    'Returns Data'[ReturnQuantity]
			)
		formatString: 0
		lineageTag: 1fb91fad-c48a-41b3-b626-168c193204e9

	measure 'Average Retail Price' =
			
			AVERAGE(
			    'Product Lookup'[ProductPrice]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e3bbdcca-5192-4067-9672-772ee69fbbed

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Returns' =
			
			COUNT(
			    'Returns Data'[ReturnQuantity]
			)
		formatString: #,0
		lineageTag: d14f1cfb-8d49-4b1c-aae2-05baf2c3bd0d

	measure 'Total Orders' =
			
			DISTINCTCOUNT(
			    'Sales Data'[OrderNumber]
			)
		formatString: #,0
		lineageTag: 32944def-fdcf-425c-ba6b-4b829216b598

	measure 'Total Customers' =
			
			DISTINCTCOUNT(
			    'Sales Data'[CustomerKey]
			)
		formatString: #,0
		lineageTag: bd6c6b10-6b0f-4f50-8970-0095c45fd7a9

	measure 'Return Rate' =
			
			DIVIDE(
			    [Quantity Returned],
			    [Quantity Sold],
			    "No Sales"
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 47484ec7-d9b1-4011-88ca-d142762d4210

	measure 'Bulk Orders' =
			
			CALCULATE(
			    [Total Orders],
			    'Sales Data'[OrderQuantity] > 1
			)
		formatString: #,0
		lineageTag: 3303d387-373d-44bd-81ce-0e78d5c2130d

	measure 'Weekend Orders' =
			
			CALCULATE(
			    [Total Orders],
			    'Calendar Lookup'[Weekend] = "Weekend"
			)
		formatString: #,0
		lineageTag: e5da7f9e-3a76-4bd3-9d7e-9cac9292b5b6

	measure 'Bike Returns' =
			
			CALCULATE(
			    [Total Returns],
			    'Product Categories Lookup'[CategoryName] = "Bikes"
			)
		formatString: #,0
		lineageTag: 1edeafee-838f-4ad0-a4be-978629bf264b

	measure 'Bike Sales' =
			
			CALCULATE(
			    [Quantity Sold],
			    'Product Categories Lookup'[CategoryName] = "Bikes"
			)
		formatString: #,0
		lineageTag: 943edc28-fd28-47b3-9b04-f0bcb25a1c04

	measure 'Bike Return Rate' =
			
			CALCULATE(
			    [Return Rate],
			    'Product Categories Lookup'[CategoryName] = "Bikes"
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f5cfe7e0-c26c-486f-8874-b832f9b69c0a

	measure 'All Orders' =
			
			CALCULATE(
			    [Total Orders],
			    ALL(
			        'Sales Data'
			    )
			)
		formatString: #,0
		lineageTag: d97b74d2-2c27-4e1b-be27-a6afd6565eab

	measure '% of All Orders' =
			
			DIVIDE(
			    [Total Orders],
			    [All Orders]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 346271cf-557e-471d-9077-e718f3263e96

	measure 'Overall Average Price' =
			
			CALCULATE(
			    [Average Retail Price],
			    ALL(
			        'Product Lookup'
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0d468256-de17-438f-89d8-d185007ec006

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'All Returns' =
			
			CALCULATE(
			    [Total Returns],
			    ALL(
			        'Returns Data'
			    )
			)
		formatString: #,0
		lineageTag: f2b44cc0-8a2d-45f5-a4e0-3017b9a334bb

	measure '% of All Returns' =
			
			DIVIDE(
			    [Total Returns],
			    [All Returns]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eb2aa539-1000-40ac-9b38-d1d47452d401

	measure 'High Ticket Orders' =
			
			CALCULATE(
			    [Total Orders],
			    FILTER(
			        'Product Lookup',
			        'Product Lookup'[ProductPrice] > [Overall Average Price]
			    )
			)
		formatString: #,0
		lineageTag: 3c02b2d3-9827-4ea5-b4cc-ea4e49ec003e

	measure 'Total Revenue' = ```
			
			SUMX(
			    'Sales Data',
			    'Sales Data'[OrderQuantity] * 
			    RELATED(
			        'Product Lookup'[ProductPrice]
			    )
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3acf0126-40b0-4de7-b7d5-741a3aa2da17

	measure 'Average Revenue per Customer' = ```
			
			DIVIDE(
			    [Total Revenue],
			    [Total Customers]
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ff627d41-6d71-4a34-8ea1-1c91be0230a9

	measure 'Total Cost' =
			
			SUMX(
			    'Sales Data',
			    'Sales Data'[OrderQuantity] *
			    RELATED(
			        'Product Lookup'[ProductCost]
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b043f3af-3af4-413e-850e-d725ffbd114e

	measure 'Total Profit' =
			
			[Total Revenue] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 856f797d-9e31-4b62-b145-c1df243b04eb

	measure 'YTD Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    DATESYTD(
			        'Calendar Lookup'[Date]
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f5960668-1cde-471c-9dd6-81decc53145a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Previous Month Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8d976d06-91f4-463b-a7bb-acd6158d119e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Target' =
			
			[Previous Month Revenue] * 1.1
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 212a3317-3901-45b6-aae8-52856b427122

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '10-day Rolling Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    DATESINPERIOD(
			        'Calendar Lookup'[Date],
			        MAX(
			            'Calendar Lookup'[Date]
			        ),
			        -10,
			        DAY
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3fed4972-3ea7-4023-a724-fa023491ddfa

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Previous Month Returns' =
			
			CALCULATE(
			    [Total Returns],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: fb0aa718-f8ec-4b66-942f-04938e84310e

	measure 'Previous Month Orders' =
			
			CALCULATE(
			    [Total Orders],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: #,0
		lineageTag: 7fa1c14a-4510-42b8-ab88-54f525aec420

	measure 'Previous Month Profit' =
			
			CALCULATE(
			    [Total Profit],
			    DATEADD(
			        'Calendar Lookup'[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 556a80c5-01de-4b91-8849-14624f63e9d7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Order Target' =
			
			[Previous Month Orders] * 1.1
		formatString: #,0
		lineageTag: 799c9397-97a2-4d6a-a53b-1273a62ea469

	measure 'Profit Target' =
			
			[Previous Month Profit] * 1.1
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4ee96f34-620d-4c8c-b4c4-311030b1233e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '90-day Rolling Profit' =
			
			CALCULATE(
			    [Total Profit],
			    DATESINPERIOD(
			        'Calendar Lookup'[Date],
			        MAX(
			            'Calendar Lookup'[Date]
			        ),
			        -90,
			        DAY
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 84100def-6528-4dd6-8fbf-0c4ca7ec7c47

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Revenue (Customer Detail)' =
			
			IF(
			    HASONEVALUE(
			        'Customer Lookup'[CustomerKey]
			    ),
			    [Total Revenue],
			    "-"
			)
		lineageTag: bdfe4080-f8ba-41f8-93fa-bb6e000978b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders (Customer Detail)' =
			
			IF(
			    HASONEVALUE(
			        'Customer Lookup'[CustomerKey]
			    ),
			    [Total Orders],
			    "-"
			)
		formatString: 0
		lineageTag: 5bb8022f-a633-4db1-9d66-c364d5dfdc9c

	measure 'Order Target Gap' = [Total Orders] - [Order Target]
		formatString: 0
		lineageTag: 7991c154-e6ed-429a-bc08-d8e99a740d42

	measure 'Revenue Target Gap' = [Total Revenue] - [Revenue Target]
		formatString: #,0.###############\ "zł";-#,0.###############\ "zł";#,0.###############\ "zł"
		lineageTag: d29a8045-0457-4e1e-8619-5d12ce8a2802

		annotation PBI_FormatHint = {"currencyCulture":"pl-PL"}

	measure 'Profit Target Gap' = [Total Profit] - [Profit Target]
		formatString: #,0.###############\ "zł";-#,0.###############\ "zł";#,0.###############\ "zł"
		lineageTag: f819bb43-da5b-4cde-84cf-066431cace0b

		annotation PBI_FormatHint = {"currencyCulture":"pl-PL"}

	measure 'Adjusted Price' = [Average Retail Price] * (1 + 'Price Adjustment (%)'[Price Adjustment % Value])
		formatString: #,0.###############\ "zł";-#,0.###############\ "zł";#,0.###############\ "zł"
		lineageTag: 877f599b-e99a-4a53-8660-1b6c8c6da0fb

		annotation PBI_FormatHint = {"currencyCulture":"pl-PL"}

	measure 'Adjusted Revenue' = ```
			
			SUMX(
			    'Sales Data',
			    'Sales Data'[OrderQuantity] * 
			    [Adjusted Price]
			)
			```
		formatString: #,0.###############\ "zł";-#,0.###############\ "zł";#,0.###############\ "zł"
		lineageTag: 24a85b4b-f79c-4519-869e-6595aa4a1157

		annotation PBI_FormatHint = {"currencyCulture":"pl-PL"}

	measure 'Adjusted Profit' = [Adjusted Revenue] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: defa545d-d5b0-4321-864c-30d8bc760caf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Measure Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

