table 'Price Adjustment (%)'
	lineageTag: 385a479a-9fde-4f7b-a797-005fe2c424d2

	measure 'Price Adjustment % Value' = SELECTEDVALUE('Price Adjustment (%)'[Price Adjustment %], 0)
		lineageTag: b6e03ba3-cc53-450c-8cc9-04aa8337b3fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Adjustment %'
		lineageTag: 46ca4c2e-d45d-49ce-b272-d3049133a8f9
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Price Adjustment (%)' = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.1)

	annotation PBI_Id = 460b4c27059548c08573ad2bedfba8a9

