table 'Sales Data'
	lineageTag: e6a10cce-2856-4698-ae0f-bad817a66874

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: a4b7caee-b478-4f05-be0a-ea377d25b5b6
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 83ce02e6-f313-4d5e-8984-036725a070c3
		summarizeBy: none
		sourceColumn: StockDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: db57dff4-4ec7-41b1-9856-b84d44320de8
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1aac1c48-67b2-4dd1-af1f-c2bd85ac92f9
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 20c90c52-17a6-47d3-b2e2-b5387629cb0e
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c2efbbfe-7719-4257-b966-cbf8623c55a7
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: ea4bb199-2895-4766-b4e9-ac2b565ad49d
		summarizeBy: sum
		sourceColumn: OrderLineItem

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 995925f1-70d8-4abb-8dc2-eee1cd6b881b
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column 'Quantity Type' =
			
			IF(
			    'Sales Data'[OrderQuantity] > 1,
			    "Multiple Items",
			    "Single Item"
			)
		lineageTag: 2e430a0d-6b03-4c0a-982f-ed5dc91f038f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sales Data' = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Artur\Documents\workspace\Power BI\AdvendureWorks Project\raw data\Sales Data"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

